### ISSUE TITLE
apriltag3_ros error

### ISSUE THREAD

**Issue by crankler** [UMich-BipedLab/AprilTag_ROS#2]
HI, thank you for your share 
When I compier all the package for front end, I try to input :
>roslaunch apriltag3_ros apriltag3_ros.launch 
 
and there show the error:
>../umich/devel/lib/apriltag3_ros/apriltag3_pub: symbol lookup error:
../umich/devel/lib/apriltag3_ros/apriltag3_pub: undefined symbol: tag36artoolkit_create

so how to change this error?

**Comment by brucejk** [comment]
H crankleri,

Thank you for using our package! I will try my best to help you to solve your issue.

Have you made the apriltag3 library first? 

For example, if your directory is structured as follow:
`workspace/catkin_ws/src/apriltag3_ros`, 
then go to `workspace/catkin_ws/src/apriltag3_ros/apriltag3`.

Do the following:
1. `mkdir build`
2. `cmake ..`
3. `make`

Lastly, go to ` workspace/catkin_ws` and do `catkin_make`

Please let me know if that works!

**Comment by crankler** [comment]
Thank you for your reply and sorry to bother you again, I try the following step:
1. `catkin_make` (only include AprilTag_msgs, LiDARTag_msgs, alignment_msgs)
2. git clone AprilTag_ROS package and LiDARTag, sync_lidartag_apriltag
3. do what you suggest and I  try to  input  `catkin_make`, the error shows:
>CMakeFiles/apriltag3_pub.dir/src/apriltag3_ros.cpp.o: In function `apriltag3_detector_ros::Node::spin(int, char**)':
apriltag3_ros.cpp:(.text+0x714c): undefined reference to `tag36artoolkit_create'
apriltag3_ros.cpp:(.text+0x7153): undefined reference to `tag36h10_create'
apriltag3_ros.cpp:(.text+0x7161): undefined reference to `tag36artoolkit_destroy'
apriltag3_ros.cpp:(.text+0x7172): undefined reference to `tag36h10_destroy'
apriltag3_ros.cpp:(.text+0x71a0): undefined reference to `tag25h7_create'
apriltag3_ros.cpp:(.text+0x74db): undefined reference to `tag25h7_destroy'
collect2: error: ld returned 1 exit status
AprilTag_ROS/CMakeFiles/apriltag3_pub.dir/build.make:226: recipe for target '../umich/devel/lib/apriltag3_ros/apriltag3_pub' failed
make[2]: *** [../umich/devel/lib/apriltag3_ros/apriltag3_pub] Error 1
CMakeFiles/Makefile2:586: recipe for target 'AprilTag_ROS/CMakeFiles/apriltag3_pub.dir/all' failed
make[1]: *** [AprilTag_ROS/CMakeFiles/apriltag3_pub.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I test these pkg  under 'melodic' and Ubuntu 18.04.
so it just seems I get a wrong path for apriltag3, what should I do to make it work?

**Comment by brucejk** [comment]
Based on the error, it seems like you didn't compile the apriltag3 library. You need to `make` the apriltag3 library first, then `catkin_make` the apriltag3_ros package. 

First, let's remove unnecessary dependencies and only compile AprilTag_ROS and apriltag_msg (i.e., removing LiDARTag and LiDARTag_msgs)

Second, you need to `make` the apriltag library, which does not depend on the ROS library. If your directory is structured as follow:
`workspace/catkin_ws/src/apriltag3_ros`, 
then go to `workspace/catkin_ws/src/apriltag3_ros/apriltag3`.

Do the following:
1. `mkdir build`
2. `cmake ..`
3. `make`

Completing the above steps should compile the apriltag library. 
Lastly, go to ` workspace/catkin_ws` and do `catkin_make` to compile the AprilTag_ROS package. 

Please try and let me know if this works!

**Comment by crankler** [comment]
I have try  to make your apriltag3 library everytime, and I find the reason.
and I change a line in your cmakelist.txt,  I add `build` in the `PATH`
```
find_library(APRILTAG3_LIBRARY
	NAMES apriltag
	PATHS ${APRILTAG3_DIR}/build/lib
)
```
Thank you again for your help!
