### ISSUE TITLE
No thing shows in the image view

### ISSUE THREAD

**Issue by NamDinhRobotics** [UMich-BipedLab/AprilTag_ROS#3]
Hello Author, I am very interested in this package,

However, when I run a bag file: extrinsic_train15.bag
in [link:](https://drive.google.com/drive/folders/1yhR0WnqLXhR_ga-TnGr85BNqz5H2_Shc)

And I tried to run the .launch file with topic name:
        image_topic: "/camera/color/image_raw" 

But nothing shows in the image result, 

Would you show me a bag file example, and how to config the launch file?

Thank you so much,

**Comment by brucejk** [comment]
Hi, 

1. Have you successfully build the package?
2. Can you provide what is the output of the terminal?
2. You should see a window popped up and show the detection results.

**Comment by NamDinhRobotics** [comment]
Hi,
1. I succeed 
2. This is my terminal output:
 started roslaunch server http://dinhnambkhn:46479/

SUMMARY
========

PARAMETERS
 * /apriltag3_ros/blur_percent: 0.3
 * /apriltag3_ros/check_num_tag: True
 * /apriltag3_ros/detection_array_topic: /apriltag3_ros/ap...
 * /apriltag3_ros/detection_topic: /apriltag3_ros/ap...
 * /apriltag3_ros/hamming: 0.0
 * /apriltag3_ros/image_topic: /camera/color/ima...
 * /apriltag3_ros/num_tag: 2
 * /apriltag3_ros/tag_family: tag16h5
 * /apriltag3_ros/tag_size: 0.3
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    apriltag3_ros (apriltag3_ros/apriltag3_pub)

ROS_MASTER_URI=http://localhost:11311

process[apriltag3_ros-1]: started with pid [27038]
######################  ROS  ######################

-->Initializing ROS...
-->done!
-->Initializing NODE...
argc:1
argv:0x7fffb3142838
-->In Node() constructor!
camera_image_topic: /camera/color/image_raw
OpenCV Version used: 3.2.0
[ INFO] [1617859321.545629893]: waiting for IMAGE...

(view:27038): GLib-GObject-CRITICAL **: 14:22:01.553: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(view:27038): GLib-GObject-CRITICAL **: 14:22:01.603: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[ INFO] [1617859321.742080757]: ...Finished waiting for IMAGE!!
Creating apriltag_detector...
Starting the APRILTAG LOOP
-->creating tag16h5 family
-->created tag16h5 family

3. I saw the window, but it only shows a black view

Would you figure out the problem? and what is your exact bag file, and .lauch file?

Thank you,

**Comment by NamDinhRobotics** [comment]
Hi, 
I want to use these bag file provided in LiDARTag, [https://github.com/UMich-BipedLab/LiDARTag](url)
bag file here: [https://drive.google.com/drive/folders/19w13uJNMax9_fNIzmFZwzYq2LpJsjKKh](url)

Please help me,
Thank you so much,

**Comment by brucejk** [comment]
Hi, 

It looks like your glib is not working properly so you have `(view:27038): GLib-GObject-CRITICAL **: 14:22:01.553: g_object_unref: assertion 'G_IS_OBJECT (object)' failed` error and I think it is the reason why your view window is black.

You need to check your dependency. 

I just tried the package again and this is my output:
![Screenshot from 2021-04-09 12-37-15](https://user-images.githubusercontent.com/26856926/114212969-6bbd9a80-9930-11eb-8eee-7bb47cb8a647.png)

**Comment by NamDinhRobotics** [comment]
Hi,
Thank you for your response,
So I need to reinstall glib?
Would you give me the exact bag file name, and launch file, that you use in bellow example?

**Comment by brucejk** [comment]
I used the same bag you tried to use and the launch file is the same in the package.
I think it is working but you can't see it. Can you use `rostopic hz /apriltag3_ros/apriltag3_tag_detections_array` to see what the output is?

**Comment by NamDinhRobotics** [comment]
Hi,
Thank you for your response,
After I install glib, this is the output:
ROS_MASTER_URI=http://localhost:11311

process[apriltag3_ros-1]: started with pid [16756]
######################  ROS  ######################

-->Initializing ROS...
-->done!
-->Initializing NODE...
argc:1
argv:0x7fff703386a8
-->In Node() constructor!
camera_image_topic: /camera/color/image_raw

(view:16756): GLib-GObject-CRITICAL **: 23:51:57.662: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
OpenCV Version used: 3.2.0
[ INFO] [1618325517.665499287]: waiting for IMAGE...

(view:16756): GLib-GObject-CRITICAL **: 23:51:57.708: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[ INFO] [1618325517.860712547]: ...Finished waiting for IMAGE!!
Creating apriltag_detector...
Starting the APRILTAG LOOP
-->creating tag16h5 family
-->created tag16h5 family

And also, when I used 
rostopic hz /apriltag3_ros/apriltag3_tag_detections_array
this is the output:
subscribed to [/apriltag3_ros/apriltag3_tag_detections_array]
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages
no new messages

Would you have any suggestion?

**Comment by brucejk** [comment]
The package does receive the images and run the detector. It is weird that your rostopic has nothing. I have two things that I would like to clarify:

1. Did you open another terminal to check rostopic list?
2. Have you built the AprilTag library first?
